[core]
port = "1056"
#port = "unix:/tmp/gaurun.sock"
workers = 8
queues = 8192
notification_max = 100
shutdown_timeout = 30
# pid = "/tmp/gaurun.pid"
# allows_empty_message = true

[android]
apikey = "apikey for FCM"
enabled = true
timeout = 5 # sec
keepalive_timeout = 30
keepalive_conns = 4
retry_max = 1
use_v1 = false
project = ""
credentials_file = "v1cred.json"

[ios]
token_auth_key_path = "./keys/key.p8"
token_auth_key_id = "auth key"
token_auth_team_id = "auth team id"
sandbox = true
enabled = true
timeout = 5
keepalive_timeout = 30
keepalive_conns = 6
retry_max = 1

[log]
access_log = "stdout"
error_log = "stderr"
level = "info"
